version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - EMAIL_USER=youremail@example.com
      - EMAIL_PASS=yourpassword
